#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export LATENT_SKETCHPAD_ROOT="${LATENT_SKETCHPAD_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"
export LATENT_SKETCHPAD_WORKSPACE_ROOT="${LATENT_SKETCHPAD_WORKSPACE_ROOT:-$(cd "$LATENT_SKETCHPAD_ROOT/.." && pwd)}"
export LATENT_SKETCHPAD_CONDA_ENV="${LATENT_SKETCHPAD_CONDA_ENV:-sketchpad-clean}"

export LATENT_SKETCHPAD_QWEN_PATH="${LATENT_SKETCHPAD_QWEN_PATH:-$LATENT_SKETCHPAD_WORKSPACE_ROOT/models/Qwen2.5-VL-7B-Instruct}"
export LATENT_SKETCHPAD_DECODER_PATH="${LATENT_SKETCHPAD_DECODER_PATH:-$LATENT_SKETCHPAD_WORKSPACE_ROOT/models/Latent-Sketchpad.Sketch_Decoder/sketch_decoder_qwen25_vl.ckpt}"
export LATENT_SKETCHPAD_IMAGE_ROOT="${LATENT_SKETCHPAD_IMAGE_ROOT:-$LATENT_SKETCHPAD_WORKSPACE_ROOT/unimrg/datasets/spatialviz}"

export LATENT_SKETCHPAD_3DPROJECT_ROOT="${LATENT_SKETCHPAD_3DPROJECT_ROOT:-$LATENT_SKETCHPAD_IMAGE_ROOT/latent_sketchpad_3dproject_currentstyle_3329}"
export LATENT_SKETCHPAD_3DPROJECT_TRAIN="${LATENT_SKETCHPAD_3DPROJECT_TRAIN:-$LATENT_SKETCHPAD_3DPROJECT_ROOT/train.json}"
export LATENT_SKETCHPAD_3DPROJECT_VAL="${LATENT_SKETCHPAD_3DPROJECT_VAL:-$LATENT_SKETCHPAD_3DPROJECT_ROOT/val.json}"
export LATENT_SKETCHPAD_3DPROJECT_TEST="${LATENT_SKETCHPAD_3DPROJECT_TEST:-$LATENT_SKETCHPAD_3DPROJECT_ROOT/test.json}"

export WANDB_MODE="${WANDB_MODE:-offline}"
export WANDB_DISABLED="${WANDB_DISABLED:-true}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$HOME/.triton/latent-sketchpad}"
export LATENT_SKETCHPAD_PYTHON_BIN="${LATENT_SKETCHPAD_PYTHON_BIN:-python}"
export LATENT_SKETCHPAD_DEEPSPEED_BIN="${LATENT_SKETCHPAD_DEEPSPEED_BIN:-deepspeed}"
