#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export LATENT_SKETCHPAD_ROOT="${LATENT_SKETCHPAD_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"
export LATENT_SKETCHPAD_WORKSPACE_ROOT="${LATENT_SKETCHPAD_WORKSPACE_ROOT:-$(cd "$LATENT_SKETCHPAD_ROOT/.." && pwd)}"
export LATENT_SKETCHPAD_CONDA_ENV="${LATENT_SKETCHPAD_CONDA_ENV:-sketchpad-qwen35-cu128}"

export LATENT_SKETCHPAD_QWEN35_PATH="${LATENT_SKETCHPAD_QWEN35_PATH:-$LATENT_SKETCHPAD_WORKSPACE_ROOT/models/Qwen3.5-4B}"
export LATENT_SKETCHPAD_QWEN35_STAGE1_PATH="${LATENT_SKETCHPAD_QWEN35_STAGE1_PATH:-$LATENT_SKETCHPAD_ROOT/outputs/spatialviz_merged_stage1_qwen35_full}"
export LATENT_SKETCHPAD_DS_Z2_CONFIG="${LATENT_SKETCHPAD_DS_Z2_CONFIG:-$LATENT_SKETCHPAD_WORKSPACE_ROOT/LLaMA-Factory/examples/deepspeed/ds_z2_config.json}"
export LATENT_SKETCHPAD_DECODER_PATH="${LATENT_SKETCHPAD_DECODER_PATH:-$LATENT_SKETCHPAD_WORKSPACE_ROOT/models/Latent-Sketchpad.Sketch_Decoder/sketch_decoder_qwen25_vl.ckpt}"
export LATENT_SKETCHPAD_IMAGE_ROOT="${LATENT_SKETCHPAD_IMAGE_ROOT:-$LATENT_SKETCHPAD_WORKSPACE_ROOT/unimrg/datasets/spatialviz}"
export LATENT_SKETCHPAD_IMAGE_DIR="${LATENT_SKETCHPAD_IMAGE_DIR:-$LATENT_SKETCHPAD_WORKSPACE_ROOT}"

export LATENT_SKETCHPAD_3DPROJECT_ROOT="${LATENT_SKETCHPAD_3DPROJECT_ROOT:-$LATENT_SKETCHPAD_IMAGE_ROOT/latent_sketchpad_3dproject_currentstyle_3329}"
export LATENT_SKETCHPAD_3DPROJECT_TRAIN="${LATENT_SKETCHPAD_3DPROJECT_TRAIN:-$LATENT_SKETCHPAD_3DPROJECT_ROOT/train.json}"
export LATENT_SKETCHPAD_3DPROJECT_VAL="${LATENT_SKETCHPAD_3DPROJECT_VAL:-$LATENT_SKETCHPAD_3DPROJECT_ROOT/val.json}"
export LATENT_SKETCHPAD_3DPROJECT_TEST="${LATENT_SKETCHPAD_3DPROJECT_TEST:-$LATENT_SKETCHPAD_3DPROJECT_ROOT/test.json}"
export LATENT_SKETCHPAD_3DPROJECT_TRAIN_SMOKE32="${LATENT_SKETCHPAD_3DPROJECT_TRAIN_SMOKE32:-$LATENT_SKETCHPAD_3DPROJECT_ROOT/train_smoke32.json}"

export LATENT_SKETCHPAD_SPATIALVIZ_MERGED_ROOT="${LATENT_SKETCHPAD_SPATIALVIZ_MERGED_ROOT:-$LATENT_SKETCHPAD_IMAGE_ROOT/latent_sketchpad_spatialviz_merged_qwen35}"
export LATENT_SKETCHPAD_SPATIALVIZ_MERGED_TRAIN="$LATENT_SKETCHPAD_SPATIALVIZ_MERGED_ROOT/train.json"
export LATENT_SKETCHPAD_SPATIALVIZ_MERGED_VAL="$LATENT_SKETCHPAD_SPATIALVIZ_MERGED_ROOT/val.json"
export LATENT_SKETCHPAD_SPATIALVIZ_MERGED_TEST="$LATENT_SKETCHPAD_SPATIALVIZ_MERGED_ROOT/test.json"

export WANDB_MODE="${WANDB_MODE:-online}"
export WANDB_DISABLED="${WANDB_DISABLED:-false}"
export WANDB_DIR="${WANDB_DIR:-$LATENT_SKETCHPAD_ROOT/wandb}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$HOME/.triton/latent-sketchpad-qwen35}"
export LATENT_SKETCHPAD_PYTHON_BIN="${LATENT_SKETCHPAD_PYTHON_BIN:-python}"
export LATENT_SKETCHPAD_DEEPSPEED_BIN="${LATENT_SKETCHPAD_DEEPSPEED_BIN:-deepspeed}"
